export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const USERTABLE_ID = process.env.NEXT_PUBLIC_APPWRITE_USERTABLE_ID!;
export const POSTSTABLE_ID = process.env.NEXT_PUBLIC_APPWRITE_POSTSTABLE_ID!;
export const TEAMMEMBERS_ID = process.env.NEXT_PUBLIC_APPWRITE_TEAMMEMBERS_ID;
