import { IoDocumentTextOutline } from "react-icons/io5";

export const notifications = [
  {
    icon: IoDocumentTextOutline,
    title: "New Files available",
    color: "#F10075",
    date: "10 hours ago",
    link: "#",
    id: 1,
  },
  {
    icon: IoDocumentTextOutline,
    title: "New Files available",
    color: "#F10075",
    date: "10 hours ago",
    link: "#",
    id: 2,
  },
  {
    icon: IoDocumentTextOutline,
    title: "New Files available",
    color: "#F10075",
    date: "10 hours ago",
    link: "#",
    id: 2,
  },
  {
    icon: IoDocumentTextOutline,
    title: "New Files available",
    color: "#F10075",
    date: "10 hours ago",
    link: "#",
    id: 2,
  },
  {
    icon: IoDocumentTextOutline,
    title: "New Files available",
    color: "#F10075",
    date: "10 hours ago",
    link: "#",
    id: 2,
  },
  {
    icon: IoDocumentTextOutline,
    title: "New Files available",
    color: "#F10075",
    date: "10 hours ago",
    link: "#",
    id: 2,
  },
  {
    icon: IoDocumentTextOutline,
    title: "New Files available",
    color: "#F10075",
    date: "10 hours ago",
    link: "#",
    id: 2,
  },
  {
    icon: IoDocumentTextOutline,
    title: "New Files available",
    color: "#F10075",
    date: "10 hours ago",
    link: "#",
    id: 2,
  },
  {
    icon: IoDocumentTextOutline,
    title: "New Files available",
    color: "#F10075",
    date: "10 hours ago",
    link: "#",
    id: 2,
  },
  {
    icon: IoDocumentTextOutline,
    title: "New Files available",
    color: "#F10075",
    date: "10 hours ago",
    link: "#",
    id: 2,
  },
  {
    icon: IoDocumentTextOutline,
    title: "New Files available",
    color: "#F10075",
    date: "10 hours ago",
    link: "#",
    id: 2,
  },
  {
    icon: IoDocumentTextOutline,
    title: "New Files available",
    color: "#F10075",
    date: "10 hours ago",
    link: "#",
    id: 2,
  },
];
