export const paragraph1 =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisis leo et bibendum pretium. Suspendisse ligula neque, ultrices nec interdum faucibus, pharetra et libero. Vestibulum viverra molestie nunc. Sed quis aliquet leo. In vel posuere tortor. Donec eros turpis, dictum vel vehicula viverra, facilisis in mauris. Praesent id aliquam eros, in semper est.Aenean pellentesque magna ut nibh lobortis, sit amet vulputate sem tristique. Ut ac ultrices lectus, id volutpat nisi. Aenean ipsum augue, mollis at sodales mollis, varius eu erat. Fusce accumsan rhoncus risus non feugiat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisis leo et bibendum pretium. Suspendisse ligula neque, ultrices nec interdum faucibus, pharetra et libero. Vestibulum viverra molestie nunc. Sed quis aliquet leo. In vel posuere tortor. Donec eros turpis, dictum vel vehicula viverra, facilisis in mauris. Nullam rhoncus enim ligula, sit amet suscipit turpis dignissim non.";

export const paragraph2 =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisis leo et bibendum pretium. Suspendisse ligula neque, ultrices nec interdum faucibus, pharetra et libero. Vestibulum viverra molestie nunc. Sed quis aliquet leo. In vel posuere tortor. Donec eros turpis, dictum vel vehicula viverra, facilisis in mauris. Praesent id aliquam eros, in semper est.";

export const paragraph3 =
  "Donec facilisis leo et bibendum pretium. Suspendisse ligula neque, ultrices nec interdum faucibus, pharetra et libero. Vestibulum viverra molestie nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eros turpis, dictum vel vehicula viverra, facilisis in mauris. Nullam rhoncus enim ligula, sit amet suscipit turpis dignissim non. Phasellus deserunt. Convallis perspiciatis fusce fermentum accumsan, arcu aliquam, velit venenatis augue proin, enim etiam dolor. Aenean ipsum augue, mollis at sodales mollis, varius eu erat.";

export const paragraph4 =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisis leo et bibendum pretium. Suspendisse ligula neque, ultrices nec interdum faucibus, pharetra et libero. Vestibulum viverra molestie nunc. Sed quis aliquet leo. In vel posuere tortor. Donec eros turpis, dictum vel vehicula viverra, facilisis in mauris. Nullam rhoncus enim ligula, sit amet suscipit turpis dignissim non. Proin consequat purus sit amet blandit sollicitudin. Aliquam in consequat libero. Morbi sollicitudin dignissim erat laoreet interdum. Phasellus magna velit, consectetur iaculis tincidunt placerat, semper non sem. Mauris in eleifend libero.";

export const paragraph5 =
  "Proin consequat purus sit amet blandit sollicitudin. Aliquam in consequat libero. Morbi sollicitudin dignissim erat laoreet interdum. Phasellus magna velit, consectetur iaculis tincidunt placerat, semper non sem. Mauris in eleifend libero. Mauris vitae nibh sed felis aliquet dictum sed egestas mauris. Sed varius est ac nulla eleifend sagittis. Praesent id aliquam eros, in semper est. Maecenas ex enim, ornare ac auctor sit amet, interdum et justo. Aenean pellentesque magna ut nibh lobortis, sit amet vulputate sem tristique. Ut ac ultrices lectus, id volutpat nisi. Aenean ipsum augue, mollis at sodales mollis, varius eu erat. Image by lookstudio on Freepik";

export const tags = [{ id: "frieds", tag: "Friends", link: "#" }];
